### PR TITLE
multirat_v1

### PR DESCRIPTION
**Pull request by grandjeanlab**
corrected https://github.com/CoBrALab/RABIES/issues/97 including @gdevenyi 's comments 
added new multiRAT registration script for added robustness.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hi @grandjeanlab what registration call were you comparing this new one against?

**Comment by grandjeanlab** [comment]
@gdevenyi, I don't understand your question because I am a noob to GitHub and barely managed a pull request.

**Comment by gdevenyi** [comment]
You did a great job with the PR. I'm asking about the registration scripts.

What registration script were you comparing against? Is it:
https://github.com/CoBrALab/RABIES/blob/master/rabies/shell_scripts/null_nonlin.sh

I just noticed, this script does nothing, all the convergence numbers are "0".

I would be basing registration on my size and resolution based generator script,
https://github.com/CoBrALab/RABIES/blob/master/rabies/shell_scripts/antsRegistration_affine_SyN.sh

**Comment by grandjeanlab** [comment]
The changes to rabies/shell_scripts/null_nonlin.sh is to correct #97
I tried all registration scripts for my application, but couldn't get something descent. 

I ended up writing rabies/shell_scripts/multiRAT_registration.sh using rabies/shell_scripts/light_SyN_registration.sh as a template. 

Specifically, it seems more robust if the anatomical have ghost/ringing artefacts and/or very large FOV. Once implemented into rabies, I will test it into the full mutliRAT dataset

**Comment by Gab-D-G** [comment]
The PR will be merged. Note that in the future, if you want to try an alternative registration script with the proper format to replace one of the pre-coded ones, you can simply provide the path to your alternative script instead of requiring the new script to be included in the core program.

**Pull request merged**
